# Generated by Django 6.0.7 on 2026-08-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='num_documento',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('RC', 'Registro Civil'), ('PA', 'Pasaporte')], default='CC', max_length=10, null=True),
        ),
    ]
