# Generated by Django 6.0.7 on 2026-08-04 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamiento', '0002_customuser_num_documento_customuser_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialista',
            name='consultorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='especialistas', to='agendamiento.consultorio'),
        ),
    ]
