# Generated by Django 6.0.7 on 2026-08-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamiento', '0003_especialista_consultorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado_cita',
            field=models.CharField(choices=[('Programada', 'Programada'), ('En_Sala', 'En Sala'), ('En_Atencion', 'En Atención'), ('Atendida', 'Atendida'), ('Cancelada', 'Cancelada'), ('No_Asistio', 'No Asistió'), ('Pendiente_Reubicacion', 'Pendiente de Reubicación')], default='Programada', max_length=30),
        ),
    ]
