# Generated by Django 6.0.7 on 2026-08-17 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamiento', '0003_alter_customuser_options_and_more'),
        ('agendamiento', '0005_alter_cita_estado_cita'),
    ]

    operations = [
    ]
