# Generated by Django 6.0.7 on 2026-08-17 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamiento', '0006_merge_20260817_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialista',
            name='consultorio_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='especialistas_asignados', to='agendamiento.consultorio'),
        ),
    ]
